//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AssemblyCSharp_ChatSocketWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AssemblyCSharp.ChatSocket), typeof(System.Object));
		L.RegFunction("getInstance", getInstance);
		L.RegFunction("Connect", Connect);
		L.RegFunction("sendMsg", sendMsg);
		L.RegFunction("ReadInt", ReadInt);
		L.RegFunction("ReadShort", ReadShort);
		L.RegFunction("closeSocket", closeSocket);
		L.RegFunction("New", _CreateAssemblyCSharp_ChatSocket);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("offset", get_offset, set_offset);
		L.RegVar("end", get_end, set_end);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateAssemblyCSharp_ChatSocket(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				AssemblyCSharp.ChatSocket obj = new AssemblyCSharp.ChatSocket();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: AssemblyCSharp.ChatSocket.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getInstance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			AssemblyCSharp.ChatSocket o = AssemblyCSharp.ChatSocket.getInstance();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Connect(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AssemblyCSharp.ChatSocket obj = (AssemblyCSharp.ChatSocket)ToLua.CheckObject(L, 1, typeof(AssemblyCSharp.ChatSocket));
			obj.Connect();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int sendMsg(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AssemblyCSharp.ChatSocket obj = (AssemblyCSharp.ChatSocket)ToLua.CheckObject(L, 1, typeof(AssemblyCSharp.ChatSocket));
			AssemblyCSharp.ChatRequest arg0 = (AssemblyCSharp.ChatRequest)ToLua.CheckObject(L, 2, typeof(AssemblyCSharp.ChatRequest));
			obj.sendMsg(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReadInt(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AssemblyCSharp.ChatSocket obj = (AssemblyCSharp.ChatSocket)ToLua.CheckObject(L, 1, typeof(AssemblyCSharp.ChatSocket));
			byte[] arg0 = ToLua.CheckByteBuffer(L, 2);
			int o = obj.ReadInt(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReadShort(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AssemblyCSharp.ChatSocket obj = (AssemblyCSharp.ChatSocket)ToLua.CheckObject(L, 1, typeof(AssemblyCSharp.ChatSocket));
			byte[] arg0 = ToLua.CheckByteBuffer(L, 2);
			short o = obj.ReadShort(arg0);
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int closeSocket(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AssemblyCSharp.ChatSocket obj = (AssemblyCSharp.ChatSocket)ToLua.CheckObject(L, 1, typeof(AssemblyCSharp.ChatSocket));
			obj.closeSocket();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_offset(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AssemblyCSharp.ChatSocket obj = (AssemblyCSharp.ChatSocket)o;
			int ret = obj.offset;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index offset on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_end(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AssemblyCSharp.ChatSocket obj = (AssemblyCSharp.ChatSocket)o;
			int ret = obj.end;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index end on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_offset(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AssemblyCSharp.ChatSocket obj = (AssemblyCSharp.ChatSocket)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.offset = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index offset on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_end(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AssemblyCSharp.ChatSocket obj = (AssemblyCSharp.ChatSocket)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.end = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index end on a nil value" : e.Message);
		}
	}
}

