//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_AndroidJavaClassWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.AndroidJavaClass), typeof(UnityEngine.AndroidJavaObject));
		L.RegFunction("New", _CreateUnityEngine_AndroidJavaClass);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_AndroidJavaClass(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				string arg0 = ToLua.CheckString(L, 1);
				UnityEngine.AndroidJavaClass obj = new UnityEngine.AndroidJavaClass(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityEngine.AndroidJavaClass.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

