//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class WechatOperateScriptWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(WechatOperateScript), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("getUserInforCallback", getUserInforCallback);
		L.RegFunction("login", login);
		L.RegFunction("onShareCallBack", onShareCallBack);
		L.RegFunction("shareAchievementToWeChat", shareAchievementToWeChat);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("shareSdk", get_shareSdk, set_shareSdk);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getUserInforCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			WechatOperateScript obj = (WechatOperateScript)ToLua.CheckObject(L, 1, typeof(WechatOperateScript));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			cn.sharesdk.unity3d.ResponseState arg1 = (cn.sharesdk.unity3d.ResponseState)ToLua.CheckObject(L, 3, typeof(cn.sharesdk.unity3d.ResponseState));
			cn.sharesdk.unity3d.PlatformType arg2 = (cn.sharesdk.unity3d.PlatformType)ToLua.CheckObject(L, 4, typeof(cn.sharesdk.unity3d.PlatformType));
			System.Collections.Hashtable arg3 = (System.Collections.Hashtable)ToLua.CheckObject(L, 5, typeof(System.Collections.Hashtable));
			obj.getUserInforCallback(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int login(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WechatOperateScript obj = (WechatOperateScript)ToLua.CheckObject(L, 1, typeof(WechatOperateScript));
			obj.login();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onShareCallBack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			WechatOperateScript obj = (WechatOperateScript)ToLua.CheckObject(L, 1, typeof(WechatOperateScript));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			cn.sharesdk.unity3d.ResponseState arg1 = (cn.sharesdk.unity3d.ResponseState)ToLua.CheckObject(L, 3, typeof(cn.sharesdk.unity3d.ResponseState));
			cn.sharesdk.unity3d.PlatformType arg2 = (cn.sharesdk.unity3d.PlatformType)ToLua.CheckObject(L, 4, typeof(cn.sharesdk.unity3d.PlatformType));
			System.Collections.Hashtable arg3 = (System.Collections.Hashtable)ToLua.CheckObject(L, 5, typeof(System.Collections.Hashtable));
			obj.onShareCallBack(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int shareAchievementToWeChat(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WechatOperateScript obj = (WechatOperateScript)ToLua.CheckObject(L, 1, typeof(WechatOperateScript));
			cn.sharesdk.unity3d.PlatformType arg0 = (cn.sharesdk.unity3d.PlatformType)ToLua.CheckObject(L, 2, typeof(cn.sharesdk.unity3d.PlatformType));
			obj.shareAchievementToWeChat(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_shareSdk(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WechatOperateScript obj = (WechatOperateScript)o;
			cn.sharesdk.unity3d.ShareSDK ret = obj.shareSdk;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index shareSdk on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_shareSdk(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WechatOperateScript obj = (WechatOperateScript)o;
			cn.sharesdk.unity3d.ShareSDK arg0 = (cn.sharesdk.unity3d.ShareSDK)ToLua.CheckUnityObject(L, 2, typeof(cn.sharesdk.unity3d.ShareSDK));
			obj.shareSdk = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index shareSdk on a nil value" : e.Message);
		}
	}
}

